Datatypes
a2ndrade/q-intellij-plugin pull request #23
Opened 2018-09-10 00:44 UTC by kiniv

This is change to improve Q datatypes support.

1) Adding support for timestamp and timespan
2) Fixing few issues where plugin highlight as correct "numbers" incorrect q expressions.
Examples:
Q can have something like 1i, 1f. At the same time 1.5i, 1d or 1m is not allowed.
Also it's possible to have 1.5f, 1e7f and 1.5p, but 1e7p is not allowed again. The list can be extended.
Same issue is with lists. That was fixed to the best of my abilities
3) Expression 1. or .9 are valid floats. Now fixed.
4) Variables in q must start from alphabetic character. In the namespaces where we start with . next character must still be alphabetical. That was fixed. (.2f is now number, not user identifier)

Fixed unit tests accordingly.

Null in q can't be negative, but one of the K tests demand -0N. I hence left it in the plugin, but would like to understand if really need it.

2018-09-12 02:17 UTC, a2ndrade commented
Thanks for the PR! You can remove the test for `-0N`. That's only valid in k3. In general, there are still a few pieces that remain from k3's support (most of the K tests originally referred to k3, not k4). Besides a small naming change (see comment) and the change for `-0N`, everything else looks good.

2018-09-12 02:19 UTC, a2ndrade requested changes
minor naming changes

2018-09-12 15:49 UTC, a2ndrade commented
Also, after you make the few updates, could you squash the commits into 1. Thanks!

2018-09-13 00:21 UTC, kiniv commented
@a2ndrade Thanks for the feedback. I can't figure out how can I see what naming changes I should do. 
Should I close this PR and raise another with single commit?

2018-09-13 14:57 UTC, a2ndrade commented on src/main/resources/com/appian/intellij/k/k.flex
> +VECTOR_INT={NUMBER_INTEGER}|{Q_NIL}|{INFINITY}
@kiniv (I thought I had added a comment here but I probably forgot to submit it), the naming change was around the rules of the form `VECTOR_{TYPE}`. Could we rename them to be `{TYPE}_VECTOR_ITEM` instead? e.g.
`VECTOR_INT` --> `INT_VECTOR_ITEM`

2018-09-13 15:41 UTC, a2ndrade commented
You don't need to create a new PR. Just squash your commits and force push to your branch. The PR will be updated. e.g.
```bash
git rebase -i origin/master
```
select `r(eword)` for the first commit and `s(quash)` for the rest. Then just force push
```bash
# will force push the checkout branch (e.g. datatypes)
git push -f original HEAD
```

2018-09-24 05:59 UTC, a2ndrade commented
@kiniv would you be OK with me making the changes and pushing the code? I may have some time tomorrow. I'd like to get your changes in soon. Let me know, Thanks!

2018-09-24 11:03 UTC, kiniv commented
@a2andrade apologies for delay. Will do shortly

2018-09-24 21:51 UTC, kiniv commented
@a2ndrade I did the requested change. Would you like me to squash commits before you merge it or that was just going forward?

2018-09-24 22:24 UTC, kiniv commented
@a2ndrade I did the requested change.

2018-09-25 00:56 UTC, a2ndrade approved these changes

2018-09-25 00:56 UTC, a2ndrade commented
@kiniv thanks! Looks great. Merging now.

2018-09-25 00:57 UTC, merged