Add icons to structure view
a2ndrade/q-intellij-plugin pull request #33
Opened 2019-01-17 05:15 UTC by YuriyYatsyk

2019-01-23 23:22 UTC, a2ndrade commented on src/main/java/com/appian/intellij/k/KStructureViewElement.java
> +        if (fnDefinition.isPresent())
```suggestion
        if (fnDefinition.isPresent()) {
```

2019-01-23 23:22 UTC, a2ndrade commented on src/main/java/com/appian/intellij/k/KStructureViewElement.java
> +        else
```suggestion
        } else {
```

2019-01-23 23:22 UTC, a2ndrade commented on src/main/java/com/appian/intellij/k/KStructureViewElement.java
> +          return element.isInternal() ? KIcons.PRIVATE_VARIABLE: KIcons.PUBLIC_VARIABLE;
```suggestion
          return element.isInternal() ? KIcons.PRIVATE_VARIABLE: KIcons.PUBLIC_VARIABLE;
        }
```

2019-01-23 23:23 UTC, a2ndrade commented
@YuriyYatsyk could you please:

1) rebase your branch to remove the merge commit?
2) update the conditional block to include braces (to match the code style of the rest of the codebase)

Thanks!

2019-01-23 23:24 UTC, a2ndrade requested changes
@YuriyYatsyk could you please:

1) rebase your branch to remove the merge commit?
2) update the conditional block to include braces (to match the code style of the rest of the codebase)

Thanks!

2019-01-24 05:27 UTC, YuriyYatsyk commented on src/main/java/com/appian/intellij/k/KStructureViewElement.java
> +          return element.isInternal() ? KIcons.PRIVATE_VARIABLE: KIcons.PUBLIC_VARIABLE;
done

2019-02-12 22:52 UTC, YuriyYatsyk commented
Are there any other issues with pull request? If you'd rather not accept these changes, please say so. 
I have other improvements that I would like to contribute, but I don't want pull requests just hanging there. Is there some process that you'd like me to follow?

2019-03-05 21:49 UTC, a2ndrade commented
@YuriyYatsyk I apologize for the delay. I'll definitely merge these changes (and any other improvements you may have) Thanks! I just hadn't had time to do it. I'll do it in the following days, though. Thank you for your patience.

2019-03-07 01:03 UTC, merged